import streamlit as st
import pandas as pd
import numpy as np
from PIL import Image
import base64

CATEGORIES = ('Frozen Desserts', 'Chicken Breast', 'Beverages', 'Soy/Tofu',
       'Vegetable', 'Pie', 'Chicken', 'Dessert', 'Southwestern U.S.',
       'Sauces', 'Stew', 'Black Beans', 'Lactose Free', 'Weeknight',
       'Yeast Breads', 'Whole Chicken', 'High Protein', 'Cheesecake',
       'Free Of...', 'High In...', 'Brazilian', 'Breakfast', 'Breads',
       'Bar Cookie', 'Brown Rice', 'Oranges', 'Pork', 'Low Protein',
       'Asian', 'Potato', 'Cheese', 'Halibut', 'Meat', 'Lamb/Sheep',
       'Very Low Carbs', 'Spaghetti', 'Scones', 'Drop Cookies',
       'Lunch/Snacks', 'Beans', 'Punch Beverage', 'Pineapple',
       'Low Cholesterol', '< 30 Mins', 'Quick Breads', 'Sourdough Breads',
       'Curries', 'Chicken Livers', 'Coconut', '< 60 Mins', 'Savory Pies',
       'Poultry', 'Steak', 'Healthy', 'Lobster', 'Rice', 'Apple',
       'Broil/Grill', 'Spreads', 'Crab', 'Jellies', 'Pears', 'Chowders',
       'Cauliflower', 'Candy', 'Chutneys', 'White Rice', 'Tex Mex',
       'Bass', 'German', 'Fruit', 'European', 'Smoothies', 'Hungarian',
       'Manicotti', 'Onions', 'New Zealand', 'Chicken Thigh & Leg',
       'Indonesian', 'Greek', 'Corn', 'Lentil', 'Summer',
       'Long Grain Rice', 'Southwest Asia (middle East)', 'Spanish',
       'Dutch', 'Gelatin', 'Tuna', 'Citrus', 'Berries', 'Peppers',
       'Salad Dressings', 'Clear Soup', 'Mexican', 'Raspberries',
       'Crawfish', 'Beef Organ Meats', 'Strawberry', 'Shakes',
       'Short Grain Rice', '< 15 Mins', 'One Dish Meal', 'Spicy', 'Thai',
       'Cajun', 'Oven', 'Microwave', 'Russian', 'Melons', 'Swiss',
       'Papaya', 'Veal', 'Roast', 'Potluck', 'Orange Roughy', 'Canadian',
       'Caribbean', 'Mussels', 'Medium Grain Rice', 'Japanese', 'Penne',
       'Elk', 'Colombian', 'Gumbo', 'Roast Beef', 'Perch', 'Vietnamese',
       'Rabbit', 'Christmas', 'Lebanese', 'Turkish', 'Kid Friendly',
       'Vegan', 'For Large Groups', 'Whole Turkey', 'Chinese', 'Grains',
       'Yam/Sweet Potato', 'Native American', 'Meatloaf', 'Winter',
       'Trout', 'African', 'Ham', 'Goose', 'Pasta Shells', 'Stocks',
       "St. Patrick's Day", 'Meatballs', 'Whole Duck', '< 4 Hours',
       'Scandinavian', 'Greens', 'Catfish', 'Dehydrator', 'Duck Breasts',
       'Savory', 'Stir Fry', 'Polish', 'Spring', 'Deer', 'Wild Game',
       'Pheasant', 'No Shell Fish', 'Collard Greens', 'Tilapia', 'Quail',
       'Refrigerator', 'Moroccan', 'Pressure Cooker', 'Squid', 'Korean',
       'Plums', 'Danish', 'Creole', 'Mahi Mahi', 'Tarts', 'Spinach',
       'Hawaiian', 'Homeopathy/Remedies', 'Austrian', 'Thanksgiving',
       'Moose', 'Bath/Beauty', 'Swedish', 'High Fiber', 'Kosher',
       'Norwegian', 'Household Cleaner', 'Ethiopian', 'Belgian',
       'Australian', 'Pennsylvania Dutch', 'Bear', 'Scottish', 'Tempeh',
       'Cuban', 'Turkey Breasts', 'Cantonese', 'Tropical Fruits',
       'Peanut Butter', 'Canning', 'Szechuan', 'Portuguese', 'Summer Dip',
       'Costa Rican', 'Duck', 'Sweet', 'Nuts', 'Filipino', 'Welsh',
       'Camping', 'Pot Pie', 'Polynesian', 'Mango', 'Cherries',
       'Egyptian', 'Chard', 'Lime', 'Lemon', 'Brunch', 'Toddler Friendly',
       'Kiwifruit', 'Whitefish', 'South American', 'Malaysian', 'Octopus',
       'Nigerian', 'Mixer', 'Venezuelan', 'Halloween', 'Stove Top',
       'Bread Machine', 'Georgian', 'South African', 'Finnish', 'No Cook',
       'Deep Fried', 'Beginner Cook', 'Steam', 'Small Appliance',
       'Nepalese', 'Palestinian', 'Egg Free', 'Easy', 'Czech',
       'Icelandic', 'Hunan', 'Avocado', 'Iraqi', 'Pakistani',
       'Chocolate Chip Cookies', 'Chilean', 'Puerto Rican', 'Ecuadorean',
       'Hanukkah', 'Breakfast Eggs', 'Cambodian', 'Honduran', 'Sudanese',
       'Mongolian', 'Peruvian', 'Peanut Butter Pie', 'Ham And Bean Soup',
       'Bread Pudding', 'Margarita', 'Bean Soup', 'Turkey Gravy',
       'Spaghetti Sauce', 'Freezer', 'Lemon Cake', 'Buttermilk Biscuits',
       'Black Bean Soup', 'Gluten Free Appetizers', 'Somalian',
       'Ice Cream', 'Snacks Sweet', 'Main Dish Casseroles', 'Pot Roast',
       'Potato Soup', 'Broccoli Soup', 'Apple Pie', 'Oatmeal',
       'Soups Crock Pot', 'Roast Beef Crock Pot', 'Artichoke',
       'Key Lime Pie', 'Chicken Crock Pot', 'Wheat Bread',
       'Mushroom Soup', 'Breakfast Casseroles', 'Grapes',
       'Macaroni And Cheese', 'Mashed Potatoes', 'Desserts Fruit',
       'Birthday', 'Pumpkin', 'Indian', 'Baking', 'Inexpensive',
       'Beef Liver', 'Memorial Day', 'Guatemalan', 'Coconut Cream Pie',
       'Labor Day')

KEYWORDS = ('Lunch/Snacks',
 'High In...',
 'Nigerian',
 'Mashed Potatoes',
 'Ice Cream',
 'Chinese',
 'Short Grain Rice',
 'Iraqi',
 'Citrus',
 'Hungarian',
 'Creole',
 'Pasta Shells',
 'Chicken Thigh & Leg',
 'Turkey Breasts',
 'Homeopathy/Remedies',
 'Indian',
 'Russian',
 'Asian',
 'Broil/Grill',
 'Belgian',
 'Apple',
 'New Zealand',
 'Nuts',
 'German',
 'Salad Dressings',
 'Papaya',
 'Candy',
 'Winter',
 'Summer',
 'Reynolds Wrap Contest',
 '< 4 Hours',
 'Filipino',
 'Ham',
 'Mixer',
 'picy',
 'Australian',
 'Chard',
 'Canadian',
 'Fruit',
 'Corn',
 '< 30 Mins',
 'Swiss',
 'Scandinavian',
 'Squid',
 'Avocado',
 'Turkish',
 'From Scratch',
 'rom Scratch',
 'Pears',
 'Coconut',
 'Honduran',
 'Mongolian',
 'Spanish',
 'Oatmeal',
 'unch/Snacks',
 'Elk',
 'Austrian',
 'Dutch',
 'Artichoke',
 'Spaghetti',
 'Thanksgiving',
 'icrowave',
 'Beef Barley Soup',
 'Oven',
 'Refrigerator',
 'Beef Crock Pot',
 'Japanese',
 'Black Beans',
 'One Dish Meal',
 'Halibut',
 'Meatloaf',
 'Strawberries Desserts',
 'Pork Crock Pot',
 'Swedish',
 'Beverages',
 'Grains',
 'Low Protein',
 'Chicken Stew',
 'Vietnamese',
 'Baking',
 'Inexpensive',
 'Savory',
 'Breakfast Potatoes',
 'Thai',
 'Christmas',
 'Catfish',
 'Quick Breads',
 'otluck',
 'Crock Pot Slow Cooker',
 'Coconut Desserts',
 'Egg Free',
 'Cookie & Brownie',
 'Potato',
 'Punch Beverage',
 'Spring',
 'Microwave',
 '< 15 Mins',
 'Eggs Breakfast',
 'Costa Rican',
 'rock Pot Slow Cooker',
 'ice',
 'Portuguese',
 'Nepalese',
 'Yeast Breads',
 'Stew',
 'Cheesecake',
 'Gumbo',
 'Whole Chicken',
 'Desserts Easy',
 'Rice',
 'Low Cholesterol',
 'Chilean',
 'Shakes',
 'Penne',
 'Gelatin',
 'Beans',
 'ative American',
 'Szechuan',
 'Peruvian',
 'Healthy',
 'Onions',
 'Plums',
 'Kosher',
 'Bean Soup',
 'Greens',
 'Duck Breasts',
 'Moroccan',
 'Beginner Cook',
 'Potluck',
 'Vegan',
 'Dehydrator',
 'Native American',
 'South American',
 'Cajun',
 'Weeknight',
 'Stir Fry',
 'Pressure Cooker',
 'Scottish',
 'Easy',
 'Tempeh',
 'Goose',
 'Pineapple',
 'Deep Fried',
 'Indonesian',
 'Hunan',
 'No Shell Fish',
 'Tomato Sauce',
 'Peppers',
 'Beef Organ Meats',
 'Chocolate Chip Cookies',
 'Tuna',
 'Hanukkah',
 'Pakistani',
 'No Bake Cookie',
 'Chicken Livers',
 'Puerto Rican',
 'Hawaiian',
 'No Cook',
 'Icelandic',
 'Caribbean',
 'Brazilian',
 'Mexican',
 'High Protein',
 'Malaysian',
 'Beef Sandwiches',
 'Lamb/Sheep',
 'Whole Duck',
 'Cheese',
 'High In... Diabetic Friendly',
 'Perch',
 'Memorial Day',
 'Kid Friendly',
 'Cucumber',
 'Halloween Cocktail',
 'Spicy',
 'Crab',
 'Lemon',
 'Tropical Fruits',
 'Served Hot New Years',
 '< 60 Mins',
 'Fish Halibut',
 'Pot Roast',
 'Baked Beans',
 'Brown Rice',
 'European',
 'Danish',
 'Cabbage',
 'Lactose Free',
 'Grapes',
 'Trout',
 'Lobster',
 'South African',
 'Somalian',
 'Southwestern U.S.',
 'College Food',
 'Sweet',
 'Pumpkin',
 'African',
 'Pot Pie',
 'Canning',
 'Jellies',
 'Guatemalan',
 'Stove Top',
 'Bass',
 'High Fiber',
 'Peanut Butter',
 'Frozen Desserts',
 'Tilapia',
 'Poultry',
 'Duck',
 'Meat',
 'runch',
 'Stocks',
 'Welsh',
 'Orange Roughy',
 'Bath/Beauty',
 'Medium Grain Rice',
 'Melons',
 'Palestinian',
 'Lime',
 'Raspberries',
 'Norwegian',
 'Smoothies',
 'Ramadan',
 'Colombian',
 'Very Low Carbs',
 'Georgian',
 'Sauces',
 'Octopus',
 'Pheasant',
 'Manicotti',
 'Crawfish',
 'Roast',
 'frican',
 'Navy Bean Soup',
 'Finnish',
 'Pie',
 'Labor Day',
 'Freezer',
 "St. Patrick's Day",
 'Cauliflower',
 'Kiwifruit',
 'Whole Turkey',
 'Czech',
 'Lime Desserts',
 'Bread Machine',
 'Spinach',
 'Tortilla Soup',
 'Collard Greens',
 'Breakfast',
 'White Rice',
 'Pork Loin',
 'Savory Pies',
 'Pasta Elbow',
 'Strawberry',
 'Halloween',
 'Brunch',
 'Breads',
 'Beef Kidney',
 'Tex Mex',
 'Free Of...',
 'Long Grain Rice',
 'Soy/Tofu',
 'Whitefish',
 'Roast Beef',
 'Korean',
 'Mango',
 'Beef Liver',
 'Meatballs',
 'Vegetable',
 'Cherries',
 'Bear',
 'Chowders',
 'Greek',
 'Rabbit',
 'Deer',
 'Yam/Sweet Potato',
 'Breakfast Eggs',
 'Birthday',
 'Chicken',
 'Small Appliance',
 'Moose',
 'Southwest Asia (middle East)',
 'Mahi Mahi',
 'Household Cleaner',
 'Beef Sauces',
 'Berries',
 'Oranges',
 'Ethiopian',
 'Wild Game',
 'exican',
 'Chicken Stews',
 'Steak',
 'Lentil',
 'Oysters',
 'outh American',
 'Veal',
 'Steam',
 'Chicken Breast',
 'Mussels',
 'Pork',
 'Curries',
 'Sudanese',
 'Chinese New Year',
 'Pennsylvania Dutch',
 'Ecuadorean',
 'Dessert',
 'For Large Groups',
 'Cranberry Sauce',
 'Bar Cookie',
 "t. Patrick's Day",
 'Clear Soup',
 'Camping',
 'Dairy Free Foods',
 'Cantonese',
 'Cambodian',
 'For Large Groups Holiday/Event',
 'Spreads',
 'Marinara Sauce',
 'Lebanese',
 'mall Appliance',
 'Venezuelan',
 'Cuban',
 'Polish',
 'Egyptian',
 'Polynesian',
 'Quail',
 'Toddler Friendly')
image = Image.open("./code/images/header.jpg")
st.markdown(" # * SSIE: 510 | Final Project: Decision Support System | Recipe Recommender System :cooking: *")
st.image(image)
st.markdown(
        "A Decision Support System by The Edge <a href='https://github.com/jackmleitch/whatscooking-deployment' > <img src='https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Octicons-mark-github.svg/600px-Octicons-mark-github.svg.png' width='20' height='20' > </a> ",
        unsafe_allow_html=True,
    )
st.markdown(" ## Given a list of ingredients, and criteria what can I make? :strawberry: ")

st.sidebar.markdown(" ## Review Filters:")

minrating = st.sidebar.slider('Averge Recipe Rating:', 0, 5, 2)
reviews = st.sidebar.slider('# People Reviewed the Recipe:', 1, 2892, 30)

st.sidebar.markdown(" ## Nutrional Information Filters:")
carbcontent = st.sidebar.slider('Carbohydrate Content (g/serving):', 0, 108294, 30)

categories = st.sidebar.multiselect("Select The Categories Which You Want To Explore:", CATEGORIES)
keywords = st.sidebar.multiselect("Select The Keyword You Resonate With:", KEYWORDS)


def download_link(object_to_download, download_filename, download_link_text):
    """
    Generates a link to download the given object_to_download.

    object_to_download (str, pd.DataFrame):  The object to be downloaded.
    download_filename (str): filename and extension of file. e.g. mydata.csv, some_txt_output.txt
    download_link_text (str): Text to display for download link.

    Examples:
    download_link(YOUR_DF, 'YOUR_DF.csv', 'Click here to download data!')
    download_link(YOUR_STRING, 'YOUR_STRING.txt', 'Click here to download your text!')

    """
    if isinstance(object_to_download,pd.DataFrame):
        object_to_download = object_to_download.to_csv(index=False)

    # some strings <-> bytes conversions necessary here
    b64 = base64.b64encode(object_to_download.encode()).decode()

    return f'<a href="data:file/txt;base64,{b64}" download="{download_filename}">{download_link_text}</a>'

#data = data.drop("Images",axis=1)
@st.cache
def load_data(url):
    data = read_csv(url)
    return data

data_load_state = st.image('./code/images/giphy.gif')

data = pd.read_csv("https://ssie510dss.s3.amazonaws.com/masterdata.csv")


filtered_data = data.loc[(data["Rating"] >= minrating)]


data_load_state.table(filtered_data.sort_values(by="Rating",ascending=False).head().style.hide_index())

if st.button('Download the data shown here? Click me!!'):
    tmp_download_link = download_link(data.head(), 'RecipesMatchingYourChoices.csv', 'Click here to download your data!')
    st.markdown(tmp_download_link, unsafe_allow_html=True)


st.markdown("## Thanks for visiting!")
st.write("If you enjoyed using the application, Click the button to celebrate.")
btn = st.button("Celebrate!")
if btn:
    st.balloons()
